### ISSUE TITLE
Error occurs when the IP list , including the #

### ISSUE THREAD

**Issue by fnifni** [deep-security/aws-waf#1]
The IP list may contain a lot of comments (#) .
```
$ python ip_list_to_set.py -d 21 -u username -p xxxxxxxx -t tenant_name --dryrun
***********************************************************************
* DRY RUN ENABLED. NO CHANGES WILL BE MADE
***********************************************************************
Traceback (most recent call last):
  File "ip_list_to_set.py", line 385, in <module>
    if __name__ == '__main__': main()
  File "ip_list_to_set.py", line 381, in main
    context.create_ip_set(ip_list)
  File "ip_list_to_set.py", line 321, in create_ip_set
    updates = self._convert_ds_addresses_to_waf(ds_list)
  File "ip_list_to_set.py", line 274, in _convert_ds_addresses_to_waf
    addresses = self._parse_ds_addresses(ds_list)
  File "ip_list_to_set.py", line 239, in _parse_ds_addresses
    if "#" in address: address = split('#').strip() # remove any comments
NameError: global name 'split' is not defined
```

**Comment by marknca** [comment]
@fnifni apologies on the delay. I've resolved the issue now. Please pull and give it another shot
